TEST_DATA = [
    ("Play Minecraft with my right hand.", {"entities": [[0, 4, "COMMAND"], [5, 14, "MODE"], [23, 28, "ORIENTATION"], [29, 33, "LANDMARK"]]}),
    ("Play Minecraft with my left hand.", {"entities": [[0, 4, "COMMAND"], [5, 14, "MODE"], [23, 27, "ORIENTATION"], [28, 32, "LANDMARK"]]}),
    ("Start Minecraft using my right hand to control the mouse.", {"entities": [[0, 5, "COMMAND"], [6, 15, "MODE"], [25, 30, "ORIENTATION"], [31, 35, "LANDMARK"], [39, 56, "ACTION"]]}),
    ("Start Minecraft using my left hand to control the mouse.", {"entities": [[0, 5, "COMMAND"], [6, 15, "MODE"], [25, 29, "ORIENTATION"], [30, 34, "LANDMARK"], [38, 55, "ACTION"]]}),
    ("Start Minecraft using an index pinch to right click the mouse.", {"entities": [[0, 5, "COMMAND"], [6, 15, "MODE"], [25, 36, "POSE"], [40, 61, "ACTION"]]}),
    ("Start Minecraft using an index pinch to left click the mouse.", {"entities": [[0, 5, "COMMAND"], [6, 15, "MODE"], [25, 36, "POSE"], [40, 60, "ACTION"]]}),
    ("I want to play pokemon and walk up when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 34, "ACTION"], [49, 53, "POSE"]]}),
    ("I want to play pokemon and walk down when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"]]}),
    ("I want to play pokemon and walk left when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"]]}),
    ("I want to play pokemon and walk right when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 37, "ACTION"], [52, 56, "POSE"]]}),
    ("I want to play pokemon and walk up when I make a fist with my right hand.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 34, "ACTION"], [49, 53, "POSE"], [62, 67, "ORIENTATION"], [68, 72, "LANDMARK"]]}),
    ("I want to play pokemon and walk down when I make a fist with my right hand.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"], [64, 69, "ORIENTATION"], [70, 74, "LANDMARK"]]}),
    ("I want to play pokemon and walk left when I make a fist with my right hand.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"], [64, 69, "ORIENTATION"], [70, 74, "LANDMARK"]]}),
    ("I want to play pokemon and walk right when I make a fist with my right hand.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 37, "ACTION"], [52, 56, "POSE"], [65, 70, "ORIENTATION"], [71, 75, "LANDMARK"]]}),
    ("I want to play pokemon and walk up when I make a fist with my left hand.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 34, "ACTION"], [49, 53, "POSE"], [62, 66, "ORIENTATION"], [67, 71, "LANDMARK"]]}),
    ("I want to play pokemon and walk down when I make a fist with my left hand.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"], [64, 68, "ORIENTATION"], [69, 73, "LANDMARK"]]}),
    ("I want to play pokemon and walk left when I make a fist with my left hand.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"], [64, 68, "ORIENTATION"], [69, 73, "LANDMARK"]]}),
    ("I want to play pokemon and walk right when I make a fist with my left hand.", {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 37, "ACTION"], [52, 56, "POSE"], [65, 69, "ORIENTATION"], [70, 74, "LANDMARK"]]}),
    ("I want to play tetris and rotate the piece when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 42, "ACTION"], [57, 61, "POSE"]]}),
    ("I want to play tetris and move the piece left when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 45, "ACTION"], [60, 64, "POSE"]]}),
    ("I want to play tetris and move the piece right when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 46, "ACTION"], [61, 65, "POSE"]]}),
    ("I want to play tetris and move the piece down when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 45, "ACTION"], [60, 64, "POSE"]]}),
    ("I want to play tetris and hold the piece when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [55, 59, "POSE"]]}),
    ("I want to play tetris and drop the piece when I make a fist.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [55, 59, "POSE"]]}),
    ("I want to play tetris and save the piece when I make a fist with my right hand.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [55, 59, "POSE"], [68, 73, "ORIENTATION"], [74, 78, "LANDMARK"]]}),
    ("I want to play tetris and rotate the piece when I thwip with my right hand.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 42, "ACTION"], [50, 55, "POSE"], [64, 69, "ORIENTATION"], [70, 74, "LANDMARK"]]}),
    ("I want to play tetris and move the piece left when I thwip with my left hand.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 45, "ACTION"], [53, 58, "POSE"], [67, 71, "ORIENTATION"], [72, 76, "LANDMARK"]]}),
    ("I want to play tetris and move the piece right when I thwip with my left hand.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 46, "ACTION"], [54, 59, "POSE"], [68, 72, "ORIENTATION"], [73, 77, "LANDMARK"]]}),
    ("I want to play tetris and when I move my hand forward the piece moves down.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [33, 53, "POSE"], [58, 74, "ACTION"]]}),
    ("I want to play tetris and when I move my hand back the piece moves up.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [33, 50, "POSE"], [55, 69, "ACTION"]]}),
    ("I want to play tetris and when I pinch my thumb and index finger the piece rotates.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [33, 64, "POSE"], [69, 82, "ACTION"]]}),
    ("I want to play tetris and when I do a peace sign the piece moves left.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [38, 48, "POSE"], [53, 69, "ACTION"]]}),
    ("I want to play tetris and when I do a thumbs up the piece moves right.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [38, 47, "POSE"], [52, 69, "ACTION"]]}),
    ("I want to play tetris and when I do a strong punch the piece holds.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [38, 50, "POSE"], [55, 66, "ACTION"]]}),
    ("I want to play tetris and when I hold three fingers up the piece drops.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [38, 51, "POSE"], [59, 70, "ACTION"]]}),
    ("I want to play tetris and hold the piece when I lift my pinky finger.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [48, 68, "POSE"]]}),
    ("I want to play tetris and drop the piece when I lift my pinky finger.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [48, 68, "POSE"]]}),
    ("I want to play tetris and save the piece when I shoot a gun.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [48, 59, "POSE"]]}),
    ("I want to play tetris and rotate the piece when I do a gun pose.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 42, "ACTION"], [55, 63, "POSE"]]}),
    ("I want to play tetris and move the piece left when I do a gun pose.", {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 45, "ACTION"], [58, 66, "POSE"]]}),
]
