TRAIN_DATA = [
    ("I want to play Minecraft", {"entities": [[10, 14, "COMMAND"], [15, 24, "MODE"]]}),
    ("Start playing Minecraft with my right hand", {"entities": [[0, 5, "COMMAND"], [14, 23, "MODE"], [32, 37, "ORIENTATION"], [38, 42, "LANDMARK"]]}),
    ("Place a block down", {"entities": [[0, 13, "ACTION"]]}),
    ("I love Minecraft", {"entities": [[7, 16, "MODE"]]}),
    ("hold my fist to place a block down", {"entities": [[0, 12, "POSE"], [16, 29, "ACTION"]]}),
    ("i want to pass the ball when i have my fist up", {"entities": [[10, 23, "ACTION"], [39, 46, "POSE"]]}),
    ("i  want to kick the ball when i kick in real life", {"entities": [[11, 24, "ACTION"], [32, 36, "GESTURE"]]}),
    ("i want to activate mario with my left hand", {"entities": [[10, 18, "COMMAND"], [19, 24, "MODE"], [33, 37, "ORIENTATION"], [38, 42, "LANDMARK"]]}),
    ("I want to cast a spell with an index pinch", {"entities": [[10, 22, "ACTION"], [31, 42, "POSE"]]}),
    ("Block attacks with a thumb index pinch", {"entities": [[0, 13, "ACTION"], [21, 38, "POSE"]]}),
    ("Use the index pinch to interact with objects", {"entities": [[8, 19, "POSE"], [23, 31, "ACTION"]]}),
    ("To crouch just do a thumbs up", {"entities": [[3, 9, "ACTION"], [20, 29, "POSE"]]}),
    ("Rotate item with a three fingers pinch", {"entities": [[0, 11, "ACTION"], [19, 38, "POSE"]]}),
    ("I want to jump using three fingers", {"entities": [[10, 14, "ACTION"], [21, 34, "POSE"]]}),
    ("I want to walk in game when I show a fist", {"entities": [[10, 14, "ACTION"], [30, 41, "POSE"]]}),
    ("In Pokemon", {"entities": [[3, 10, "MODE"]]}),
    ("do", {"entities": []}),
    ("three fingers to destroy", {"entities": [[0, 13, "POSE"], [17, 24, "ACTION"]]}),
    ("I want to place down a block when I do index pinch", {"entities": [[10, 28, "ACTION"], [39, 50, "POSE"]]}),
    ("Please start Rocket League", {"entities": [[7, 12, "COMMAND"], [13, 26, "MODE"]]}),
    ("I use my left hand for navigation", {"entities": [[9, 13, "ORIENTATION"], [14, 18, "LANDMARK"], [23, 33, "ACTION"]]}),
    ("clench a fist to boost speed", {"entities": [[0, 13, "POSE"], [17, 28, "ACTION"]]}),
    ("making a kicking motion to shoot the ball towards the goal", {"entities": [[9, 23, "GESTURE"], [27, 41, "ACTION"]]}),
    ("Start body points mode", {"entities": [[0, 5, "COMMAND"], [6, 17, "MODE"]]}),
    ("Run desktop mode", {"entities": [[0, 3, "COMMAND"], [4, 11, "MODE"]]}),
    ("Activate double pinch click", {"entities": [[0, 8, "COMMAND"], [9, 27, "MODE"]]}),
    ("Begin driving mode", {"entities": [[0, 5, "COMMAND"], [6, 13, "MODE"]]}),
    ("Switch to force field", {"entities": [[0, 7, "COMMAND"], [10, 21, "MODE"]]}),
    ("Start gun move", {"entities": [[0, 5, "COMMAND"], [6, 14, "MODE"]]}),
    ("Activate head drive mode", {"entities": [[0, 8, "COMMAND"], [9, 19, "MODE"]]}),
    ("Run hit trigger mode", {"entities": [[0, 3, "COMMAND"], [4, 15, "MODE"]]}),
    ("Begin inking mode", {"entities": [[0, 5, "COMMAND"], [6, 12, "MODE"]]}),
    ("Switch to joystick mode", {"entities": [[0, 6, "COMMAND"], [10, 23, "MODE"]]}),
    ("Start minecraft elbows", {"entities": [[0, 5, "COMMAND"], [6, 22, "MODE"]]}),
    ("Activate mouse options", {"entities": [[0, 8, "COMMAND"], [9, 22, "MODE"]]}),
    ("Run navigation mode", {"entities": [[0, 3, "COMMAND"], [4, 19, "MODE"]]}),
    ("Begin nlp mode", {"entities": [[0, 5, "COMMAND"], [6, 14, "MODE"]]}),
    ("Switch to nose scroll", {"entities": [[0, 6, "COMMAND"], [10, 21, "MODE"]]}),
    ("Start pinch click mode", {"entities": [[0, 5, "COMMAND"], [6, 22, "MODE"]]}),
    ("Switch to scroll navigation", {"entities": [[0, 7, "COMMAND"], [10, 27, "MODE"]]}),
    ("Run rocket league", {"entities": [[0, 3, "COMMAND"], [4, 17, "MODE"]]}),
    ("I want to jump when I pose thumb down", {"entities": [[10, 14, "ACTION"], [27, 37, "POSE"]]}),
    ("start body points mode with my right hand", {"entities": [[0, 5, "COMMAND"], [6, 22, "MODE"], [31, 36, "ORIENTATION"], [37, 41, "LANDMARK"]]}),
    ("start desktop mode with my left hand", {"entities": [[0, 5, "COMMAND"], [6, 18, "MODE"], [27, 31, "ORIENTATION"], [32, 36, "LANDMARK"]]}),
    ("start desktop mode with my left hand to move the mouse and a left index pinch to left click", {"entities": [[0, 6, "COMMAND"], [6, 14, "MODE"], [27, 32, "ORIENTATION"], [32, 36, "LANDMARK"], [40, 54, "POSE"], [61, 77, "POSE"], [81, 91, "ACTION"]]}),
    ("I want to play rocket league and use my left elbow to left click", {"entities": [[10, 15, "COMMAND"], [15, 28, "MODE"], [40, 45, "ORIENTATION"], [45, 51, "LANDMARK"], [54, 64, "ACTION"]]}),
    ("I want to play rocket league and use my right elbow to click space", {"entities": [[10, 15, "COMMAND"], [15, 28, "MODE"], [40, 46, "ORIENTATION"], [46, 52, "LANDMARK"], [55, 66, "ACTION"]]}),
    ("Attach left click to my right elbow", {"entities": [[0, 6, "COMMAND"], [7, 17, "ACTION"], [24, 30, "ORIENTATION"], [30, 35, "LANDMARK"]]}),
    ("Attach right click to me right elbow", {"entities": [[7, 18, "ACTION"], [25, 31, "ORIENTATION"], [31, 36, "LANDMARK"]]}),
    ("Attach the mouse to my hand", {"entities": [[0, 7, "COMMAND"], [11, 17, "POSE"], [23, 27, "LANDMARK"]]}),
    ("I want to play rocket league and move left with my left elbow", {"entities": [[10, 15, "COMMAND"], [15, 28, "MODE"], [33, 42, "ACTION"], [51, 56, "ORIENTATION"], [56, 61, "LANDMARK"]]}),
    ("I want to play rocket league and move right with my right elbow", {"entities": [[10, 14, "COMMAND"], [15, 28, "MODE"], [33, 43, "ACTION"], [52, 58, "ORIENTATION"], [58, 63, "LANDMARK"]]}),
    ("I want to play rocket league and press space with my right hand", {"entities": [[10, 15, "COMMAND"], [15, 28, "MODE"], [33, 44, "ACTION"], [53, 59, "ORIENTATION"], [59, 63, "LANDMARK"]]}),
    ("play rocket league with my left hand to click the mouse", {"entities": [[0, 4, "COMMAND"], [5, 18, "MODE"], [27, 32, "ORIENTATION"], [32, 37, "LANDMARK"], [40, 55, "ACTION"]]}),
    ("switch to rocket league and use my left hand to left click the mouse", {"entities": [[0, 7, "COMMAND"], [10, 23, "MODE"], [35, 40, "ORIENTATION"], [40, 45, "LANDMARK"], [48, 68, "ACTION"]]}),
    ("activate rocket league and use my left hand to right click", {"entities": [[0, 8, "COMMAND"], [9, 22, "MODE"], [34, 39, "ORIENTATION"], [39, 44, "LANDMARK"], [47, 58, "ACTION"]]}),
    ("Start rocket league and press shift with my right elbow", {"entities": [[0, 6, "COMMAND"], [6, 19, "MODE"], [24, 35, "ACTION"], [44, 50, "ORIENTATION"], [50, 55, "LANDMARK"]]}),
    ("play minecraft and left click with my fist", {"entities": [[0, 5, "COMMAND"], [5, 15, "MODE"], [19, 29, "ACTION"], [38, 42, "POSE"]]}),
    ("play rocket league and right click with my left elbow", {"entities": [[0, 4, "COMMAND"], [5, 18, "MODE"], [23, 34, "ACTION"], [43, 48, "ORIENTATION"], [48, 53, "LANDMARK"]]}),
    ("Play Minecraft with my right hand.",
     {"entities": [[0, 4, "COMMAND"], [5, 14, "MODE"], [23, 28, "ORIENTATION"], [29, 33, "LANDMARK"]]}),
    ("Play Minecraft with my left hand.",
     {"entities": [[0, 4, "COMMAND"], [5, 14, "MODE"], [23, 27, "ORIENTATION"], [28, 32, "LANDMARK"]]}),
    ("Start Minecraft using my right hand to control the mouse.", {
        "entities": [[0, 5, "COMMAND"], [6, 15, "MODE"], [25, 30, "ORIENTATION"], [31, 35, "LANDMARK"],
                     [39, 56, "ACTION"]]}),
    ("Start Minecraft using my left hand to control the mouse.", {
        "entities": [[0, 5, "COMMAND"], [6, 15, "MODE"], [25, 29, "ORIENTATION"], [30, 34, "LANDMARK"],
                     [38, 55, "ACTION"]]}),
    ("Start Minecraft using an index pinch to right click the mouse.",
     {"entities": [[0, 5, "COMMAND"], [6, 15, "MODE"], [25, 36, "POSE"], [40, 61, "ACTION"]]}),
    ("Start Minecraft using an index pinch to left click the mouse.",
     {"entities": [[0, 5, "COMMAND"], [6, 15, "MODE"], [25, 36, "POSE"], [40, 60, "ACTION"]]}),
    ("I want to play pokemon and walk up when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 34, "ACTION"], [49, 53, "POSE"]]}),
    ("I want to play pokemon and walk down when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"]]}),
    ("I want to play pokemon and walk left when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"]]}),
    ("I want to play pokemon and walk right when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 37, "ACTION"], [52, 56, "POSE"]]}),
    ("I want to play pokemon and walk up when I make a fist with my right hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 34, "ACTION"], [49, 53, "POSE"],
                     [62, 67, "ORIENTATION"], [68, 72, "LANDMARK"]]}),
    ("I want to play pokemon and walk down when I make a fist with my right hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"],
                     [64, 69, "ORIENTATION"], [70, 74, "LANDMARK"]]}),
    ("I want to play pokemon and walk left when I make a fist with my right hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"],
                     [64, 69, "ORIENTATION"], [70, 74, "LANDMARK"]]}),
    ("I want to play pokemon and walk right when I make a fist with my right hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 37, "ACTION"], [52, 56, "POSE"],
                     [65, 70, "ORIENTATION"], [71, 75, "LANDMARK"]]}),
    ("I want to play pokemon and walk up when I make a fist with my left hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 34, "ACTION"], [49, 53, "POSE"],
                     [62, 66, "ORIENTATION"], [67, 71, "LANDMARK"]]}),
    ("I want to play pokemon and walk down when I make a fist with my left hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"],
                     [64, 68, "ORIENTATION"], [69, 73, "LANDMARK"]]}),
    ("I want to play pokemon and walk left when I make a fist with my left hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 36, "ACTION"], [51, 55, "POSE"],
                     [64, 68, "ORIENTATION"], [69, 73, "LANDMARK"]]}),
    ("I want to play pokemon and walk right when I make a fist with my left hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 22, "MODE"], [27, 37, "ACTION"], [52, 56, "POSE"],
                     [65, 69, "ORIENTATION"], [70, 74, "LANDMARK"]]}),
    ("I want to play tetris and rotate the piece when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 42, "ACTION"], [57, 61, "POSE"]]}),
    ("I want to play tetris and move the piece left when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 45, "ACTION"], [60, 64, "POSE"]]}),
    ("I want to play tetris and move the piece right when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 46, "ACTION"], [61, 65, "POSE"]]}),
    ("I want to play tetris and move the piece down when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 45, "ACTION"], [60, 64, "POSE"]]}),
    ("I want to play tetris and hold the piece when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [55, 59, "POSE"]]}),
    ("I want to play tetris and drop the piece when I make a fist.",
     {"entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [55, 59, "POSE"]]}),
    ("I want to play tetris and save the piece when I make a fist with my right hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 40, "ACTION"], [55, 59, "POSE"],
                     [68, 73, "ORIENTATION"], [74, 78, "LANDMARK"]]}),
    ("I want to play tetris and rotate the piece when I thwip with my right hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 42, "ACTION"], [50, 55, "POSE"],
                     [64, 69, "ORIENTATION"], [70, 74, "LANDMARK"]]}),
    ("I want to play tetris and move the piece left when I thwip with my left hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 45, "ACTION"], [53, 58, "POSE"],
                     [67, 71, "ORIENTATION"], [72, 76, "LANDMARK"]]}),
    ("I want to play tetris and move the piece right when I thwip with my left hand.", {
        "entities": [[10, 14, "COMMAND"], [15, 21, "MODE"], [26, 46, "ACTION"], [54, 59, "POSE"],
                     [68, 72, "ORIENTATION"], [73, 77, "LANDMARK"]]}),
]
